### ISSUE TITLE
Login on Microsoft edge is not taking all the vertical space available

### ISSUE THREAD

**Issue by angelcalvasp** [creativetimofficial/material-dashboard-pro#123]
Hi there issue team, 
today I found out that on Microsoft Edge on the login page, the vertical space of 100% isn't being applied,
I'm not so sure why though, the following screenshot is from the demo page, 

![image](https://user-images.githubusercontent.com/7502746/38522969-cabe2b5c-3c0f-11e8-99c4-666a0b3f1e62.png)

Notice all the white space on the bottom

**Comment by mtik00** [comment]
Also seen on Firefox 59.0.2 (64-bit)
![image](https://user-images.githubusercontent.com/1509355/38762878-6a0f402e-3f4e-11e8-93e2-17426f7f985c.png)

**Comment by dragosct10** [comment]
Hi! Please, to fix this issue add a padding to the div with class .page-header which can be for example: 

```css
.page-header{
  padding: 100px 0;
} 
```

Regards,
Dragos

**Comment by dragosct10** [comment]
Hi, @mtik00! I checked again and please put these properties: 

```css
.page-header{
   display: flex !important;
   height: 100%;
   min-height: 100vh;
}
```
Regards,
Dragos

**Comment by angelcalvasp** [comment]
Thanks @dragosct10

**Comment by angelcalvasp** [comment]
![image](https://user-images.githubusercontent.com/7502746/38959288-ab05b01a-4325-11e8-89c7-975525b62c77.png)

![image](https://user-images.githubusercontent.com/7502746/38959304-bc24608a-4325-11e8-96ab-36d9f8d2e03b.png)

**Comment by dragosct10** [comment]
Hi, @angelcalvasp! You also added these lines of code? 
```css
.page-header{
  padding: 100px 0;
} 
```
Regards, 
Dragos

**Comment by angelcalvasp** [comment]
yep, nada any more info you need to track downd the problem?

**Comment by dragosct10** [comment]
Hi, @angelcalvasp! Thank you for using our product. You don't need to also add the padding 100px 0; , only the below properties: 

```css
.page-header{
   display: flex !important;
   height: 100%;
   min-height: 100vh;
}
```

Regards,
Dragos

**Comment by angelcalvasp** [comment]
As stated before, it solves the issue, but another one is introduced which drags down the login towards the bottom instead of it being centered vertically like it originally was

**Comment by dragosct10** [comment]
Hi! Please give me your project link to see what is happening there. Regards, Dragos

**Comment by angelcalvasp** [comment]
Its a clean material dashboard v2.0.1 downloaded from my customer panel

**Comment by dragosct10** [comment]
Hi, @angelcalvasp! I understand but in this way, it's very hard to figure out what happens in your code. Regards, Dragos

**Comment by angelcalvasp** [comment]
Here you go, hope this helps

https://1drv.ms/u/s!AnlhbXXlXWf_op5T80C5t-NW5skpKg

**Comment by dragosct10** [comment]
Hi, @angelcalvasp! Sorry for the late response. I think you gave me a blank login page. Please see the image attached. 

<img width="1432" alt="screen shot 2018-05-02 at 11 29 52" src="https://user-images.githubusercontent.com/17456857/39513293-8e21e5cc-4dfc-11e8-974f-1917f32dd5f0.png">

Regards, 
Dragos

**Comment by mtik00** [comment]
The time I checked, ya, the form was *not* vertically centered on the page with the included fix.  It seems much closer to the bottom of the page than before.  I would prefer the div to be centered too.

**Comment by dragosct10** [comment]
Hi, @angelcalvasp! Please remove from the .container the property `padding-top: 23vh;`
<img width="157" alt="screen shot 2018-05-10 at 09 53 53" src="https://user-images.githubusercontent.com/17456857/39856335-21e43c56-5438-11e8-963d-fc06475f7dda.png">

Regards, 
Dragos

**Comment by angelcalvasp** [comment]
Nailed it sir, thank you for your time I shall close this

**Comment by angelcalvasp** [comment]
if anyone comes throught this what you need to do is add this

``` css
.page-header{
   display: flex !important;
   height: 100%;
   min-height: 100vh;
}
```

and remove this

```css
.login-page .page-header .container {
    padding-top: 23vh;
}
```
