### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by jycouet** [creativetimofficial/material-dashboard-pro#7]
Hi, 

I just boat this nice theme and I really like your work. Thank you.

I just have a question on custom colors...
In **_variables.scss** I changed: 

> $brand-primary: $blue-grey !default;

With this now, in my side bar, when I put the data-active-color to purple I have my primary color.
```
<div class="sidebar" 
          data-active-color="purple" 
          data-background-color="white" 
          data-image="./img/sidebar-4.jpg">
```

It's a bit weird to put purple to have the brand color, but it's fine.

BUT, when I put in a card purple it's going purple and not brand
```
<div class="card">
            <div class="card-header card-header-icon" data-background-color="purple">
                <i class="material-icons">language</i>
            </div>
            <div class="card-content">
                <h4 class="card-title">Location</h4>
```

How can I set the brand color to my card?
Thank you

**Comment by alexandru-paduraru** [comment]
@jycouet thank you for using our product and for pointing this out. It seems there was an error in our development process and we messed up the primary with purple. We will fix this in the next release. As a quick fix please:

1. Since the Cards needs 2 colors to create that gradient, you need to manually create the primary/blue-grey class so please go to `sass/material-dashboard/_cards.scss` and add this code at line 337

```css
    [data-background-color="blue-grey"]{
        background: linear-gradient(60deg, $blue-grey-400, $blue-grey-600);
        @include shadow-big-color($blue-grey);
    }

    [data-icon-bg-color="blue-grey"]{
        @include alert-icon-color($blue-grey);
    }
```
Compile the sass again and then everytime when you use blue-grey the card will be changed to the corresponding color.

Please let us know if that was working fine.

Best, 
Alex
